version: "3.7"
services:

  ## PHP-FPM Container ############
  app:
    build:
      args:
        user: userapi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: project
    container_name: project-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - project

  ## NGINX Container #############
  nginx:
    image: nginx:1.17-alpine
    container_name: project-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - project

networks:
  project:
    driver: bridge